### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Extra-lightwill** [Extra-lightwill/gql-sequelize-ver01#1]
- [ ] implement add Task mutation
- [ ] implement edit Task mutation 
- [ ] implement remove Task mutation 
- [ ] implement query total number of Tasks
- [ ] implement search to retrieve Tasks based on dynamic parameters

**Note:** Use connection + GraphQLList in separate queries to cover both use-cases

**Comment by Extra-lightwill** [comment]
@Neitsch 

Current commit:
 
- AFAIK, db models are mapped correctly with GraphQL models 
- db tables are created using sequelize logic in connection.js file 
- basic front-end UI is done 
- TasksMain page functions have been updated 
- Database insert for addTaskMutation is working but appears to be inserting empty object
